export const GalleryData = [
    {
        id:1,
        titile:"Web",
        image:"./images/webtwo.png"
    },
    {
        id:2,
        titile:"Android",
        image:"./images/webtwo.png"
        
    },
    {
        id:3,
        titile:"IOS",
        image:"./images/webtwo.png"
    },
    {
        id:4,
        titile:"Web",
        image:"./images/webtwo.png"
    },
    {
        id:5,
        titile:"Android",
        image:"./images/webtwo.png"
    },
    {
        id:6,
        titile:"IOS",
        image:"./images/webtwo.png"
    },
    {
        id:7,
        titile:"Web",
        image:"./images/webtwo.png"
    },
    {
        id:8,
        titile:"Android",
        image:"./images/webtwo.png"
    },
    {
        id:9,
        titile:"IOS",
        image:"./images/webtwo.png"
    },
    {
        id:10,
        titile:"Web",
        image:"./images/webtwo.png"
    },
    {
        id:11,
        titile:"Android",
        image:"./images/webtwo.png"
    },
    {
        id:12,
        titile:"IOS",
        image:"./images/webtwo.png"
    },
    {
        id:13,
        titile:"Web",
        image:"./images/webtwo.png"
    },
    {
        id:14,
        titile:"Android",
        image:"./images/webtwo.png"
    },
    {
        id:15,
        titile:"IOS",
        image:"./images/webtwo.png"
    },
  
]